export const Services = {
  service_providers: [
    {
      name: "Grand Venue",
      state: "Delhi",
      city: "New Delhi",
      price: "100000",
      service_type: "Venue",
      rating: "4.8",
    },
    {
      name: "Capture Moments",
      state: "Rajasthan",
      city: "Jaipur",
      price: "50000",
      service_type: "Photographer",
      rating: "4.7",
    },
    {
      name: "Glamourous Makeovers",
      state: "Karnataka",
      city: "Bengaluru",
      price: "35000",
      service_type: "Makeup Artist",
      rating: "4.5",
    },
    {
      name: "Dreamy Decorations",
      state: "Maharashtra",
      city: "Mumbai",
      price: "60000",
      service_type: "Decorator",
      rating: "4.6",
    },
    {
      name: "Henna Happiness",
      state: "Tamil Nadu",
      city: "Chennai",
      price: "25000",
      service_type: "Mehendi Artist",
      rating: "4.4",
    },
    {
      name: "Delicious Delights",
      state: "Uttar Pradesh",
      city: "Lucknow",
      price: "45000",
      service_type: "Food Caterers",
      rating: "4.3",
    },
    {
      name: "Groovy Beats",
      state: "Kerala",
      city: "Kochi",
      price: "40000",
      service_type: "Music/DJ",
      rating: "4.9",
    },
    {
      name: "Officiate with Love",
      state: "West Bengal",
      city: "Kolkata",
      price: "30000",
      service_type: "Officiator",
      rating: "4.8",
    },
    {
      name: "Royal Venue",
      state: "Gujarat",
      city: "Ahmedabad",
      price: "20000",
      service_type: "Venue",
      rating: "4.5",
    },
    {
      name: "Picture Perfect",
      state: "Punjab",
      city: "Chandigarh",
      price: "35000",
      service_type: "Photographer",
      rating: "4.7",
    },
    {
      name: "Bridal Blush",
      state: "Haryana",
      city: "Gurugram",
      price: "50000",
      service_type: "Makeup Artist",
      rating: "4.6",
    },
    {
      name: "Whimsical Weddings",
      state: "Delhi",
      city: "New Delhi",
      price: "100000",
      service_type: "Decorator",
      rating: "4.8",
    },
    {
      name: "Heena Harmony",
      state: "Rajasthan",
      city: "Jaipur",
      price: "50000",
      service_type: "Mehendi Artist",
    },
  ],
};
